# Spring相关配置
spring:
  # Profile配置文件的相关配置
  profiles:
    # 激活哪个Profile配置
    active: dev
  # Jackson框架相关配置
  jackson:
    # JSON结果中是否包含为null的属性的默认配置
    default-property-inclusion: non_null

# 配置Mybatis的XML文件的位置
mybatis:
  mapper-locations: classpath:mapper/*.xml

knife4j:
  enable: true
